# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

levy_alpha2nu <- function(levy_alpha, b, beta_0) {
    .Call('_rTrawl_levy_alpha2nu', PACKAGE = 'rTrawl', levy_alpha, b, beta_0)
}

levy_alpha_beta <- function(p_grid, T0, TT) {
    .Call('_rTrawl_levy_alpha_beta', PACKAGE = 'rTrawl', p_grid, T0, TT)
}

simulate_trawl_uv <- function(levy_seed, levy_par, trawl, trawl_par, T0, TT, observed_freq, b) {
    .Call('_rTrawl_simulate_trawl_uv', PACKAGE = 'rTrawl', levy_seed, levy_par, trawl, trawl_par, T0, TT, observed_freq, b)
}

simulate_trawl_mv <- function(levy_seed, levy_par, trawl, trawl_par, design_matrix, T0, TT, observed_freq, b) {
    .Call('_rTrawl_simulate_trawl_mv', PACKAGE = 'rTrawl', levy_seed, levy_par, trawl, trawl_par, design_matrix, T0, TT, observed_freq, b)
}

survival_GIG <- function(unif_seed, gamma, delta, nu, Tmax, b, observed_freq) {
    .Call('_rTrawl_survival_GIG', PACKAGE = 'rTrawl', unif_seed, gamma, delta, nu, Tmax, b, observed_freq)
}

number_parameters_trawl <- function(trawl) {
    .Call('_rTrawl_number_parameters_trawl', PACKAGE = 'rTrawl', trawl)
}

trawl_bounds <- function(trawl) {
    .Call('_rTrawl_trawl_bounds', PACKAGE = 'rTrawl', trawl)
}

trawl_x0 <- function(trawl) {
    .Call('_rTrawl_trawl_x0', PACKAGE = 'rTrawl', trawl)
}

vs_sample <- function(h, x_grid, p_grid, T0, TT, multi) {
    .Call('_rTrawl_vs_sample', PACKAGE = 'rTrawl', h, x_grid, p_grid, T0, TT, multi)
}

vs_SY <- function(h, trawl, trawl_par, beta_0, levy_alpha, include_cum1, b, include_b) {
    .Call('_rTrawl_vs_SY', PACKAGE = 'rTrawl', h, trawl, trawl_par, beta_0, levy_alpha, include_cum1, b, include_b)
}

