# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_trawl_uv <- function(levy_seed, levy_par, trawl, trawl_par, T0, TT, observed_freq, b) {
    .Call('_rTrawl_simulate_trawl_uv', PACKAGE = 'rTrawl', levy_seed, levy_par, trawl, trawl_par, T0, TT, observed_freq, b)
}

survival_GIG <- function(unif_seed, gamma, delta, nu, Tmax, b, observed_freq) {
    .Call('_rTrawl_survival_GIG', PACKAGE = 'rTrawl', unif_seed, gamma, delta, nu, Tmax, b, observed_freq)
}

